spring.application.name=msClientes

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=banking_user
spring.datasource.password=banking_password

# Propiedades del driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Propiedades de JPA e Hibernate
# 'update' permite que JPA/Hibernate actualice la base de datos para que coincida con tus entidades (Cliente, Persona)
# Ten cuidado con esto en producción, ya que puede sobrescribir datos.
# Para producción, se recomienda 'none' o 'validate'.
spring.jpa.hibernate.ddl-auto=update

# Muestra las sentencias SQL en la consola. Útil para depurar.
spring.jpa.show-sql=true

# Hibernate dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect